title: TacOps
#description: Tactical-Operations mit allen Infos zum Event!
repo:

#remote_theme: andreondra/jekyll-theme-simplex
#remote_theme: S3ler/leap-day
#remote_theme: S3ler/cayman
remote_theme: Tactical-Operations/cayman


show_downloads: false
